### ISSUE TITLE
[FR] Adittional variable pass oppurtunity to track_callback

### ISSUE THREAD

**Issue by MrDini123** [Pandentia/pylava#6]
Hi,

Would it be possible to attach additional kwargs to the `track_callback` method call? I mean when I attach my custom event handler method it'd be awesome if I Could attach more things aswell, like the current title, the guild/channel id, duration and so on.

```py
            out = self.track_callback(self)
            if isawaitable(out):
                await out
```

Thanks!

**Comment by SapphicCode** [comment]
The track callback callable can be generated when a new track is queued, thus you could simply store references to these kinds of attributes in the callable (for instance, as `lambda player: self._run_next_track(player.guild_id)`).

Closing this as unrelated to the library.
